Adding terraform setup for Grafana
GoogleCloudPlatform/fourkeys pull request #204
Opened 2021-09-08 01:30 UTC by dinagraves

This PR:
- Adds a README
- Adds a cloudbuild.yaml for easy building and deploying
- Updates the terraform installer to automatically build and deploy the dashboard

Outstanding questions:
 - Should we choose a default auth for the dashboard?

2021-09-08 02:58 UTC, dinagraves commented
Fixes https://github.com/GoogleCloudPlatform/fourkeys/issues/168

2021-09-08 03:01 UTC, dinagraves commented
The dashboard still needs more style tweaking.

2021-09-10 20:48 UTC, davidstanke requested changes
Ooooh, I <3 this! Just one request...

When I open the `dashboard_endpoint`, I get a [grafana home page](https://fourkeys-grafana-dashboard-rrwq5aqzsq-uc.a.run.app/?orgId=1), and then I have to hunt around to find the actual dashboard. Is it possible (I bet not) to generate a link directly to the dashboard? If not, can we add some instructions in the README, and maybe even echo a bit of instruction from the script, telling people how to find it?

2021-09-10 20:51 UTC, dinagraves commented
> Ooooh, I <3 this! Just one request...
> 
> When I open the `dashboard_endpoint`, I get a [grafana home page](https://fourkeys-grafana-dashboard-rrwq5aqzsq-uc.a.run.app/?orgId=1), and then I have to hunt around to find the actual dashboard. Is it possible (I bet not) to generate a link directly to the dashboard? If not, can we add some instructions in the README, and maybe even echo a bit of instruction from the script, telling people how to find it?

I think it's possible but I'd have to play with it a bit.  I think you can hardcode a dashboard ID and then link to it that way.

2021-09-15 02:27 UTC, dinagraves commented
Updated the URL but didn't test the whole terraform setup again.

2021-09-15 13:51 UTC, davidstanke commented on setup/dashboard/main.tf
> +
Per #216, let's add labels to the resources we create, so they can be bulk-deleted when troubleshooting

```suggestion
  metadata {
    labels = {"created_by":"fourkeys"}
  }
```

2021-09-15 14:28 UTC, davidstanke commented on setup/install.sh
> +DASHBOARD_URL="$(terraform output -raw dashboard_endpoint)d/yVtwoQ4nk/four-keys?orgId=1"
```suggestion
DASHBOARD_URL="$(terraform output -raw dashboard_endpoint)/d/yVtwoQ4nk/four-keys?orgId=1"
```

2021-09-15 14:31 UTC, davidstanke requested changes
It works! Just one minor text edit, and a request to add a label to the cloud-run service... TAL at the suggestions.

2021-09-16 00:31 UTC, davidstanke approved these changes

2021-09-16 00:35 UTC, merged