Add integration with circleci
GoogleCloudPlatform/fourkeys pull request #205
Opened 2021-09-09 17:14 UTC by na-ga

## About

Added circleci to CI/CD integration.

## Ref

CircleCI webhook spec: https://circleci.com/docs/2.0/webhooks/

## Example

SELECT * FROM `gcp-abema-fourkeys.four_keys.events_raw` WHERE source = "circleci" LIMIT 1

```
[
  {
    "event_type": "workflow-completed",
    "id": "0172e311-3ca9-368e-bc1b-c8ad42d971aa",
    "metadata": "{\"type\": \"workflow-completed\", \"id\": \"0172e311-3ca9-368e-bc1b-c8ad42d971aa\", \"happened_at\": \"2021-09-09T15:42:37.842Z\", \"webhook\": {\"id\": \"b5091b03-71db-45b4-b283-51bad7440725\", \"name\": \"FourKeys\"}, \"workflow\": {\"id\": \"492043ae-e3cb-49ab-bb6e-6ade80b0f682\", \"name\": \"build_and_test\", \"created_at\": \"2021-09-09T15:39:35.561Z\", \"stopped_at\": \"2021-09-09T15:42:37.667Z\", \"url\": \"https://app.circleci.com/pipelines/github/my_org_name/my_repository_name/104/workflows/492043ae-e3cb-49ab-bb6e-6ade80b0f682\", \"status\": \"success\"}, \"pipeline\": {\"id\": \"49080ee8-5b66-4c6f-9007-cdb21cf26e41\", \"number\": 104, \"created_at\": \"2021-09-09T15:39:34.860Z\", \"trigger\": {\"type\": \"webhook\"}, \"vcs\": {\"provider_name\": \"github\", \"origin_repository_url\": \"https://github.com/my_org_name/my_repository_name\", \"target_repository_url\": \"https://github.com/my_org_name/my_repository_name\", \"revision\": \"7eec5bc6fb6a6b8256fd60b10a6418859de48780\", \"commit\": {\"subject\": \"Fix test\", \"body\": \"\", \"author\": {\"name\": \"my account\", \"email\": \"my-account@email.com\"}, \"authored_at\": \"2021-09-09T15:39:29Z\", \"committer\": {\"name\": \"my account\", \"email\": \"my-account@email.com\"}, \"committed_at\": \"2021-09-09T15:39:29Z\"}, \"branch\": \"fourkeys\"}}, \"project\": {\"id\": \"3a06f674-3e67-4f37-b5be-e9375864d508\", \"name\": \"my_repository_name\", \"slug\": \"github/my_org_name/my_repository_name\"}, \"organization\": {\"id\": \"45f7dfd7-5dfa-426c-8b7c-fb83570a66d5\", \"name\": \"my_org_name\"}}",
    "time_created": "2021-09-09 15:42:37.842 UTC",
    "signature": "v1=f2f9b37d96911f1a31884c1fb823126d2c4c1422eff39bd240b548ba76f3a347",
    "msg_id": "3011779339500770",
    "source": "circleci"
  },
]
```

SELECT * FROM `gcp-abema-fourkeys.four_keys.deployments` LIMIT 2

```
[
  {
    "source": "circleci",
    "deploy_id": "f6cdcf0e-7330-3d9f-bdfe-61679f43c540",
    "time_created": "2021-09-09 15:39:56.925 UTC",
    "main_commit": "7eec5bc6fb6a6b8256fd60b10a6418859de48780",
    "changes": [
      "7eec5bc6fb6a6b8256fd60b10a6418859de48780"
    ]
  }
]
```

2021-09-10 19:54 UTC, davidstanke commented
Hi @na-ga ! Thanks for the PR! At first glance, this looks great. :) I'd like to get Dina's eyes on it as well, so expect a proper review shortly.

2021-09-14 20:12 UTC, dinagraves commented
This is so excellent!  I'm going to test it out with our installer and give more feedback.

2021-09-15 02:05 UTC, dinagraves requested changes
> CircleCI workflows may only perform testing and not deployment. Therefore, the query that generates the deployments table (view) targets the success event of the workflow that contains the name `deploy`. Is there any better way to do this?

I think this is a fine starting point.  We have to acknowledge that everyone is going to do it a little different and they'll have to find the right signals to filter out the successful deployments.  

I've tested this out manually and set it up with a CircleCI deployment sending to the Webhook.  I can confirm that it works end-to-end.

Thank you so much for this excellent work!  My only change request is to revert the files back in the other builders.  We don't need the `sys.stdout.flush()` because of how we set up the Dockerfile.

2021-09-15 02:34 UTC, dinagraves approved these changes

2021-09-15 02:34 UTC, dinagraves commented on bq-workers/github-parser/main.py
> -import sys
Thank you for being so thorough! I really appreciate it!

2021-09-15 02:37 UTC, dinagraves commented
Thank you again for this contribution!  If you haven't done so yet, feel free to join us on the #fourkeys channel on the [Google Cloud Platform Slack](https://join.slack.com/t/googlecloud-community/shared_invite/zt-m973j990-IMij2Xh8qKPu7SaHfOcCFg)!

2021-09-15 02:37 UTC, merged

2021-09-15 02:40 UTC, na-ga commented
@dinagraves @davidstanke 
Thanks for the review and the merge!

2021-09-15 02:43 UTC, na-ga commented
Thanks for the invitation to slack. I've just joined.